### ISSUE TITLE
Tasks Completed in Geneva Not Displayed in Airdrop

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/airdrop-process#9]
Tasks completed within the Geneva platform are not appearing in the airdrop section as expected. Users are unable to view the tasks they have completed in Geneva when accessing the airdrop

The task highlighted in yellow has been completed, yet it still appears in red in the airdrop section. This feedback was also provided by one of our users.

![Image](https://github.com/MXCzkEVM/airdrop-process/assets/93600163/70a97154-2dec-4d9e-b549-23d64a4ac1cf)

**Comment by hairyf** [comment]
what is the address?

**Comment by hairyf** [comment]
due to the synchronization time, the results may not be known until the next day

**Comment by SanghamitraBhowmick1993** [comment]
this is the address tested 0xcEb9B47485fdd900aE66A0ABD275d72c8518cBDf

**Comment by hairyf** [comment]
> The address **0xcEb9B47485fdd900aE66A0ABD275d72c8518cBDf** was tested, but even after a day or two, the results do not appear in green. Additionally, I am unable to access my address. It throws an application error. You can check it here: https://airdrop.moonchain.com/address/0x0795D90c6d60F7c77041862E9aE5059B4d5e0d7A

fixed

**Comment by SanghamitraBhowmick1993** [comment]
this is not working https://airdrop.moonchain.com/address/0xB99aF4FA2617091153d80F04A2BD0Ae294D36142
Steps to replicate:
1. Execute a swap and validate the geneva tasks


![Image](https://github.com/MXCzkEVM/airdrop-process/assets/93600163/300f32a3-7a8b-472d-837a-39404366b8ae)

Tx Hash: 0x8e28069c3d874a9f236aa20dbb787663deb7451ab8fb9edc665af6360539d11a
and Tx details: https://geneva-explorer.moonchain.com/tx/0x8e28069c3d874a9f236aa20dbb787663deb7451ab8fb9edc665af6360539d11a

**Comment by SanghamitraBhowmick1993** [comment]
This is still not working and is blocking weekly airdrop changes testing https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=59138748 

cc: @sheenhx @Crypto-guru-dev

**Comment by SanghamitraBhowmick1993** [comment]
working as expected, test evidence attached here https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=59138748&issue=MXCzkEVM%7Ctoken-airdrop-x2e%7C1
